# SPDX-FileCopyrightText: Copyright 2023 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause

name: flutter_local_notifications_aurora
description: The Aurora OS implementation of flutter_local_notifications.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dbus: ^0.7.8
  plugin_platform_interface: ^2.0.2
  flutter_local_notifications_platform_interface: ^7.0.0
  ## https://pub.dev/packages/package_info_plus
  package_info_plus: 3.1.2
  ## https://os-git.omprussia.ru/non-oss/flutter/flutter-plugins/-/tree/master/packages/package_info_plus/package_info_plus_aurora
  package_info_plus_aurora:
    git:
      url: git@os-git.omprussia.ru:non-oss/flutter/flutter-plugins.git
      ref: master
      path: packages/package_info_plus/package_info_plus_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        dartPluginClass: FlutterLocalNotificationsAurora
